# Generated by Django 5.1.4 on 2025-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherSeoul",
            fields=[
                ("date", models.DateTimeField(primary_key=True, serialize=False)),
                ("year", models.CharField(blank=True, max_length=10, null=True)),
                ("month", models.CharField(blank=True, max_length=10, null=True)),
                ("day", models.CharField(blank=True, max_length=10, null=True)),
                ("avg_tmp", models.FloatField(blank=True, null=True)),
                ("high_tmp", models.FloatField(blank=True, null=True)),
                ("low_tmp", models.FloatField(blank=True, null=True)),
                ("cloud_cover", models.FloatField(blank=True, null=True)),
                ("day_rain", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "weather_seoul",
                "managed": False,
            },
        ),
    ]
